### ISSUE TITLE
Getting Gauss to Recognize a Data File

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-5#19]
When I  go to my folder for challenge-week-5 and run this line from gauss Readme on my command line: 

```
gauss> var data = fs.readFileSync('data.txt').toString();
```

my computer says "no such file or directory 'data.txt'", even though I have created a data.txt file in my challenge-week-5 folder. Do you have to somehow notify gauss what directory you need to be in?

**Comment by wannabeCitizen** [comment]
Yes, this looks like a scope problem.  Not sure where you are running the
JS console from or how exactly you're using Gauss, but for that import
statement to work they would have to be running from the same root
directory.

Here's a stackoverflow answer that shows how to get data from your working
directory.  You may want to use something like this to figure out if the
working directory actually has what you think:
https://stackoverflow.com/questions/3151436/how-can-i-get-the-current-directory-name-in-javascript

**Comment by ghost** [comment]
So I experimented some more, and when I stuck data.txt in Downloads/node_modules/gauss, it worked like a charm. Thanks for pointing me in the right direction.
